### ISSUE TITLE
Can't seem to obtain AssetElement value as a string

### ISSUE THREAD

**Issue by jpsear** [Kentico/kentico-cloud-graphql-schema-generator#1]
### Brief bug description

I have a generated schema for a field that is an "AssetElement". When I try and grab the `value` field from this using GraphQL (I have a simple Apollo server exposing the API), the `value` is returned as an array. However, the schema defines the `value` as a string. Hence, I get this error:

```
"message": "String cannot represent value: [{ name: \"download.jpeg\", type: \"image/jpeg\", size: 7182, description: \"Hello\", url: \"https://assets-us-01.kc-usercontent.com:443/7af4a1c9-4f89-428d-8b96-0f3a8bad840a/5e639ff3-4096-4732-b2e6-e1ba73ee7ac1/download.jpeg\" }]",
```

### Repro steps

1. Create an asset field in a content type
2. Generate a schema using this library
3. Expose the API using Apollo (or similar) with the generated schema

![image](https://user-images.githubusercontent.com/2982712/51551711-efc9fb80-1e66-11e9-91b7-baa60adbd7eb.png)

I might be doing this completely wrong!

**Comment by Simply007** [comment]
Could you try version 1.0.1-beta for the generating?

**Comment by Simply007** [comment]
@jpsear,

may I ask you, whether you are using [javascript SDK](https://github.com/Kentico/kentico-cloud-js/tree/master/packages/delivery) for loading the items?

Example is in:
https://github.com/Kentico/cloud-boilerplate-express-apollo/blob/master/graphQL/queries.js#L22

**Comment by jpsear** [comment]
Awesome thanks, I'll give the beta a go today at some point.

I _wasn't_ using the SDK until I found the boilerplate example (before you posted) on your GitHub! I've now copied a fair amount of your code from there into my project. It's working very well. 

It's all going to be open sourced anyway, my thoughts were to create a simple GQL API server that hooks up to KC automatically and can be exposed via:

- Node
- Azure function
- AWS Lambda

etc...

See more here: https://github.com/MMTDigital/kentico-cloud-graphql-server. It's very early days right now though...

**Comment by Simply007** [comment]
That is great to hear!

In case of any question, feel free to open an issue and I would do my best to help you.

**Comment by jpsear** [comment]
Hey @Simply007 I'm yet to try this — but it's on my todo list. I will hopefully get around to it this week!

**Comment by jpsear** [comment]
Cool — updated and I now get the correct schema for an Asset type 👍

**Comment by Simply007** [comment]
great! - sending to production release!.
