### ISSUE TITLE
Use the schema generator inside node

### ISSUE THREAD

**Issue by jpsear** [Kentico/kentico-cloud-graphql-schema-generator#4]
I'm currently using the following code to use the generator in Node (not on the command line).

I am posting to make sure that this is a future-proofed way to do this? I.e.: will the structure of the modules change, breaking this code? It feels a bit clunky to have to reach into "_commonjs".

```js
const fs = require('fs')
const { SchemaGenerator } = require('kentico-cloud-graphql-schema-generator/_commonjs/schema-generator')
const { DeliveryClient } = require('kentico-cloud-delivery')
const { promisify } = require('util')

const deliveryClient = new DeliveryClient({
  enableSecuredMode: false,
  projectId: process.env.KENTICO_CLOUD_PROJECT_ID
})

const writeFile = promisify(fs.writeFile)
const generator = new SchemaGenerator(deliveryClient)

generator.getSchema()
  .then(result => writeFile('./schema/kentico-cloud-schema.graphql', result))
  .catch(error => {
    console.error('Error while writing schema to file', error)
  })
```

**Comment by Simply007** [comment]
I would use the `index.js` as it is written https://github.com/Kentico/kentico-cloud-graphql-schema-generator#run. There are couple ways, how to run the node script from another node script. I would stick with creating the [child_process](https://nodejs.org/api/process.html).

If I make any breaking changes I would definitely raise the major version number of the package.

But I agree this is not the best way to run the generator from the script.

Let me close theis issue and I will raise a feature request issue and link it with this one.

**Comment by jpsear** [comment]
Cool. I've now done this. For anyone else's benefit, here's how I did it:

```
const { exec } = require('child_process')
const { promisify } = require('util')
const asyncExec = promisify(exec)

module.exports = () => asyncExec('npm run generate-schema')
```

Assuming you have an npm script that runs the schema generator
